<?php

namespace Bdloc\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function findBooksBySearch(){

        $book = $this->createQueryBuilder('b');

        //if(){
        //$qb->where();
        //}
        
        $book->join('b.illustrator', 'i');
        $book->addSelect('i');        
        $book->join('b.colorist', 'c');
        $book->addSelect('c');        
        $book->join('b.scenarist', 's');
        $book->addSelect('s');

        $book->setFirstResult(0)
            ->setMaxResults(30);

        $query = $book->getQuery();

        $paginator = new Paginator($query);
        return $paginator;
    }
}