<?php

namespace Bdloc\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreditCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditCardRepository extends EntityRepository
{

    public function findCreditCardWithUserId($id)
    {
        $query = $this->createQueryBuilder('c')
            ->addSelect('u')
            ->join('c.user', 'u')
            ->where('u.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
    }
}
